### PR TITLE
Fix build requirements and update

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

CI builds have been failing since May 2020 because `R CMD INSTALL` couldn't find the `proj` library. This PR updates the library to the current version and adds `proj` as an explicit build dependency. I have tested this fix locally using `build-locally.py` and it works there for Linux.

### CODE REVIEW

**Comment by izahn** [comment]
Not sure about the OS X failures, and I don't have a Mac to test locally. I opened an issue at https://github.com/r-spatial/lwgeom/issues/65 to see if anyone has seen this before or has any ideas.

**Comment by dpryan79** [comment]
I did some digging and it seems the OSX error is likely due to POSTGIS_PROJ_VERSION not getting defined on OSX. That ends up getting caused by:

```
dyld: Library not loaded: @rpath/libproj.19.dylib
  Referenced from: /Users/runner/miniforge3/conda-bld/r-lwgeom_1612897471161/work/./proj_conf_test
  Reason: image not found
```

**Comment by izahn** [comment]
@conda-forge-admin, please ping team

Can we please merge this PR and fix the OSX build issue later? Build failures are unrelated to this PR, as demonstrated by the CI failures in https://github.com/conda-forge/r-lwgeom-feedstock/pull/14

**Comment by dpryan79** [comment]
@conda-forge/r Thoughts on skipping OSX for now? Given that the lack of updates is causing real-world problems I'm in favor of just skipping OSX in the short-term.

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
I'll let this sit until ~noon tomorrow German time. If there are no objections by then we can merge.

**Pull request merged**
